import os
import json
import luigi

from shellout import shellout_no_stdout, shellout
import configuration



class AnnotateVep(luigi.Task):
  """
  Annotates a database using a file generated by Ensembl VEP.
  """
  
  path = luigi.Parameter()
  database = luigi.Parameter()
  
  def run(self):
    config = configuration.get_opencga_config('pipeline_config.conf')
    command = '{opencga-root}/bin/opencga-storage.sh annotate-variants --annotator vep ' \
              '--database {database} --load {filename}'
    kwargs = {'opencga-root'    : config['root_folder'],
              'database'        : self.database,
              'filename'        : self.path}
    shellout_no_stdout(command, **kwargs)



if __name__ == '__main__':
    luigi.run()
